# Generated by Django 4.2.1 on 2023-05-21 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='isbn',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='title',
        ),
    ]
